### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vnc87** [SaltyCybernaut/PocketCHIP-flash-utils#1]
I follow all the tutorial and got:
`./PocketCHIP-flash-utils/flash-pocketchip.sh: line 17: ./chip-update-firmware.sh: Permission denied`

Why? :(

**Comment by SaltyCybernaut** [comment]
What is the result of running

`ls -hAlF PocketCHIP-flash-utils/`

**Comment by SaltyCybernaut** [comment]
Unable to verify due to a lack of details.
