### ISSUE TITLE
Raspbian / Java issue

### ISSUE THREAD

**Issue by Gun-neR** [SaltyCybernaut/PocketCHIP-flash-utils#4]
Much like https://github.com/SaltyCybernaut/PocketCHIP-flash-utils/issues/3#issue-541707103 ... that also seems to have been ignored?  I want to use the RPi but I suspect I am running into a distro based discrepancy.  I get this error in my install procedure...

pi@raspberrypi3:~/pocketchip $ sudo apt install --yes android-tools-fastboot sunxi-tools u-boot-tools openjdk-11-jdk-headless unzip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package openjdk-11-jdk-headless**

As I already have openjdk-11 installed (but not acknowledged by these commands?) and nothing in this github project has been touched in 11 months, I suspect this flash utility is just not going to be made to work for the RPi distro.  Time to break out the Linux laptop.

**Comment by Gun-neR** [comment]
Yup... java 11 was already installed...

pi@raspberrypi3:~/pocketchip $ java -version
openjdk version "11.0.2-BellSoft" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2-BellSoft+7)
OpenJDK Server VM (build 11.0.2-BellSoft+7, mixed mode)

So perhaps I am already good to go?

I ran out of space on my SD card, installing the flash collections... so just cloning to a larger SD card to try again :)

**Comment by SaltyCybernaut** [comment]
For those wanting to use a distribution/hardware not supported by the Chip flashing utility you may have some luck using the Vagrant VM mentioned on the [Archive.org](https://archive.org/details/C.h.i.p.FlashCollection) site if you are interested in trying to get this to work.
